load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# local_repository(
#     # Name of the Abseil repository. This name is defined within Abseil's
#     # WORKSPACE file, in its `workspace()` metadata
#     name = "com_google_absl",

#     # NOTE: Bazel paths must be absolute paths. E.g., you can't use ~/Source
#     path = "/home/jeff/src/github.com/abseil/abseil-cpp",
# )

http_archive(
    name = "com_google_absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)

http_archive(
    name = "com_google_glog",
    strip_prefix = "glog-master",
    urls = ["https://github.com/google/glog/archive/master.zip"],
)

# glog depends on gflags.
http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-master",
    urls = ["https://github.com/gflags/gflags/archive/master.zip"],
)
