cc_binary(
    name = "solution-1",
    srcs = ["solution-1.cc"],
    data = ["input.txt"],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_glog//:glog",
    ],
)

cc_binary(
    name = "solution-2",
    srcs = ["solution-2.cc"],
    data = ["input.txt"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/strings",
        "@com_google_glog//:glog",
    ],
)
